name: Gist Sentiment Analysis

on:
  workflow_dispatch:      # Allow manual triggers

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy vaderSentiment matplotlib seaborn requests

    - name: Run sentiment analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIST_ID: ${{ secrets.DATA_GIST_ID }}
        RESULTS_GIST_ID: ${{ secrets.RESULTS_GIST_ID }}
      run: python sentiment_analysis.py
